KapsProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include ,re_path

from django.views.static import serve

urlpatterns = [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('Kaps_admin.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Kaps_admin/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('Kaps_admin/', views.Kaps_admin, name='Kaps_admin'),
    path('pro_management/', views.pro_management, name='pro_management'),
    path('crm/', views.crm, name='crm'),
    path('sell_car/', views.sell_car, name='sell_car'),
    path('users/', views.users, name='users'),
    path('delete_user/<str:id>/', views.delete_user, name='delete_user'),
    path('proposal/', views.proposal, name='proposal'),
    path('delete_proposel/<str:id>/', views.delete_proposel, name='delete_proposel'),
    path('add_product/', views.add_product, name='add_product'),
    path('delete_car/<str:id>/', views.delete_car, name='delete_car'),
    path('admin_logout/', views.admin_logout, name='admin_logout'),
    path('search/', views.search_cars, name='search_cars'),
    path('Car_brands/', views.Car_brands, name='Car_brands'),
    path('add_brands/', views.add_brands, name='add_brands'),
    path('delete_brand/<str:id>/', views.delete_brand, name='delete_brand'),
    path('notification/', views.notification, name='notification'),
    path('dele_notification/<str:i>/<int:id>/', views.dele_notification, name='dele_notification'),
    path('career_data/', views.career_data, name='career_data'),
    path('add_careers/', views.add_careers, name='add_careers'),
    path('del_careers/<str:id>/', views.del_careers, name='del_careers'),
    path('add_happy_club/', views.add_happy_club, name='add_happy_club')   
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    #index
    path('', views.home, name='home'),
    path('futured_cars/<str:id>/', views.futured_cars, name='futured_car'),

    #products -car
    path('collections/', views.collections, name='collections'),
    path('filter/', views.filter, name='filter'),
    path('car_details/<str:id>/', views.car_details, name='car_details'),

    #kaps_assured
    path('kaps_assured/', views.kaps_assured, name='kaps_assured'),

    #about us
    path('about_us/', views.about_us, name='about_us'),

    #emi
    path('emi/', views.emi, name='emi'),

    #login
    path('login/',views.user_login, name='login'),
    path('otp/', views.otp_verification , name='otp'),
    path('resend-otp/', views.resend_otp, name='resend_otp'),
    path('logout/', views.logout, name='logout'),


    # happiness club
    path('happiness_club_view/', views.happiness_club_view, name='happiness_club_view'),

    # careers
    path('careers/', views.careers, name='career_list'),

    # find a car
    path('find_a_car/', views.find_a_car, name='find_a_car'),

    # sell your car
    path('sell_a_car/', views.sell_a_car, name='sell_a_car'),
    path('proposal-success/', views.proposal_success, name='proposal_success'),

    path('test_drive/<int:id>', views.test_drive, name='test_drive'),
    path('book_now/<int:id>', views.book_now, name='book_now'),

    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('terms_and_conditions/', views.terms_and_conditions, name='terms_and_conditions'),
]

Kaps_admin/models.py
from django.db import models

# Create your models here.


class Crm_Profile(models.Model):
    seller_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=12)
    address = models.TextField(blank=True)
    staff_name = models.CharField(max_length=100)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.seller_name} {self.staff_name}"
    

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.utils import timezone
from django.contrib.auth.hashers import make_password
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User
from Kaps_admin.models import Crm_Profile

# ==================== User Model (Customer) ======================
class UserLogin(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    mobile = models.CharField(max_length=15)
    is_active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


# ====================== Product Model (Car) =======================

class Brand(models.Model):
    Available_brands = models.CharField(max_length=50, blank=True, null=True)
    brand_description = models.TextField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.Available_brands


class Fuel_type(models.Model):
    Available_fuel_type = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.Available_fuel_type


class Transmission(models.Model):
    Transmission_type = models.CharField(max_length=20, blank=True, null=True)

    def __str__(self):
        return self.Transmission_type


class Cars(models.Model):
    brand = models.ForeignKey(Brand, null=False, on_delete=models.CASCADE, related_name='car_brand')
    fuel = models.ForeignKey(Fuel_type, null=False, on_delete=models.CASCADE, related_name='fueltype')
    model_name = models.CharField(max_length=50, blank=False, null=False)
    colour = models.CharField(max_length=20, blank=True, null=True)
    variant = models.CharField(max_length=20, null=True, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    mileage = models.IntegerField()
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_listed = models.BooleanField(default=True)
    transmission = models.ForeignKey(Transmission, null=False, on_delete=models.CASCADE, related_name='trans_type')
    inspection_rating = models.IntegerField()
    reg_year = models.IntegerField()
    reg_month = models.CharField(max_length=10, blank=True, null=True)
    km_driven = models.IntegerField()
    rto = models.CharField(max_length=100)
    insurance_validity = models.DateField()
    insurance_type = models.CharField(max_length=20, blank=True, null=True)
    no_of_owners = models.CharField(max_length=100)
    finance_available = models.BooleanField(default=False)
    emi = models.CharField(max_length=3, choices=[('Yes', 'Yes'), ('No', 'No')], default='No')  # Add this line

    # ==================== inspection-related fields ========================
    engine_rating = models.IntegerField()
    suspension_rating = models.IntegerField()
    brakes_rating = models.IntegerField()
    transmission_rating = models.IntegerField()
    interior_rating = models.IntegerField()
    wheels_tyres_rating = models.IntegerField()

    def __str__(self):
        return f"{self.reg_year} {self.model_name}"


class Car_Image(models.Model):
    car = models.ForeignKey(Cars, on_delete = models.CASCADE, related_name = 'images')
    Car_image = models.ImageField(upload_to='Car_images/',validators=[FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])


    def __str__(self):
        return f'Image of {self.car.model_name}'


# ====================== Sell Your Car Model =============================
class SellYourCar(models.Model):
    car_reg_number = models.CharField(max_length=50)
    car_model = models.CharField(max_length=50, blank=True, null=True)
    registered_year = models.IntegerField()
    brand_name = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='brand_name')
    fuel_type = models.ForeignKey(Fuel_type, on_delete=models.CASCADE, related_name='type_of_fuel')
    km_driven = models.IntegerField()
    selling_price = models.DecimalField(max_digits=10, decimal_places=2)
    images = models.ImageField(upload_to='sell_car_images/')
    proposed_user = models.ForeignKey(UserLogin,on_delete=models.CASCADE,null=True,blank=False,related_name='selled_user')
    proposed_staff = models.ForeignKey(Crm_Profile,on_delete=models.CASCADE,null=True,blank=False,related_name='selled_staf')

    def __str__(self):
        return f"{self.brand_name.Available_brands} {self.car_model} - {self.car_reg_number}"


# ============================  careers ==============================
class Career(models.Model):
    job_title = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    experience = models.CharField(max_length=100)
    description = models.TextField()
    email = models.EmailField(max_length=254)
    date_posted = models.DateField(auto_now_add=True)
    last_date_to_apply = models.DateField()

    def __str__(self):
        return self.job_title

# ========================== Happines Club ============================
class HappinessClub(models.Model):
    owner_image = models.ImageField(upload_to='happiness_club/', blank=True,)
    testimonial = models.CharField(max_length=200)




class Test_drive(models.Model):
    user_data = models.ForeignKey(UserLogin, on_delete=models.CASCADE, related_name='user')
    car_data = models.ForeignKey(Cars, on_delete=models.CASCADE, related_name='car')
    created_at = models.DateTimeField(auto_now_add=True)
    is_test = models.BooleanField(default=True)


    def __str__(self):
        return f"{self.user_data.name} {self.car_data.model_name}"


class Book_now(models.Model):
    user_data = models.ForeignKey(UserLogin, on_delete=models.CASCADE, related_name='u_data')
    car_data = models.ForeignKey(Cars, on_delete=models.CASCADE, related_name='c_data')
    created_at = models.DateTimeField(auto_now_add=True)
    is_test = models.BooleanField(default=False)


    def __str__(self):
        return f"{self.user_datas.name} {self.car_datas.model_name}"

templates/kaps_admin/add_brand.html
{% extends 'kaps_admin/admin_base.html' %}
{% block content %}
{% load static %}

<main id="main" class="main">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Add a new Product to the database</h5>
            <form method="post" enctype="multipart/form-data" id="add-product-form">
                {% csrf_token %}
                
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Brand name</label>
                    <div class="col-sm-10">
                        <input type="text" name="brand" id="id_name" class="form-control">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_description" class="col-sm-2 col-form-label">Description</label>
                    <div class="col-sm-10">
                        <textarea name="des" id="id_description" class="form-control"></textarea>
                        <div class="text-danger error-message" id="description-error"></div>
                    </div>
                </div>
                
                <div class="row mb-3">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-dark">Add Brand</button>
                    </div>
                </div>
            </form>
            
        </div>
    </div>
</main>

{% endblock %}

templates/kaps_admin/add_careers.html
{% extends 'kaps_admin/admin_base.html' %}
{% block content %}
{% load static %}

<main id="main" class="main">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Add a new Job Openings</h5>
            <form method="post" enctype="multipart/form-data" id="add-product-form">
                {% csrf_token %}
                
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Job title</label>
                    <div class="col-sm-10">
                        <input type="text" name="title" id="id_name" class="form-control">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Location</label>
                    <div class="col-sm-10">
                        <input type="text" name="location" id="id_name" class="form-control">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Experience</label>
                    <div class="col-sm-10">
                        <input type="text" name="exp" id="id_name" class="form-control">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Job discription</label>
                    <div class="col-sm-10">
                        <input type="text" name="discription" id="id_name" class="form-control">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Email</label>
                    <div class="col-sm-10">
                        <input type="text" name="email" id="id_name" class="form-control">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_last_date" class="col-sm-2 col-form-label">Application last date</label>
                    <div class="col-sm-10">
                        <input type="date" name="last_date" id="id_last_date" class="form-control">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                
                <div class="row mb-3">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-dark">Add</button>
                    </div>
                </div>
            </form>
            
        </div>
    </div>
</main>

{% endblock %}

templates/kaps_admin/add_happy_club.html
{% extends 'kaps_admin/admin_base.html' %}
{% load static %}

{% block content %}


<main id="main" class="main">
    <div class="card">
        <div class="card-body">
            <form method="POST" action="{% url 'add_happy_club' %}" enctype="multipart/form-data" id="sellCarForm">
                {% csrf_token %}
                <div class="form-row mb-3">
                    <div class="col-md-6 mb-3" style="margin-bottom: 15px;">
                        <label for="carImage">Image</label>
                        <input type="file" name="images" class="form-control-file" id="carImage">
                    </div>
                </div>
                <div class="form-row mb-3" style="margin-bottom: 15px;">
                    <div class="row mb-3" style="width: 100%;">
                        <label for="testimonial" class="col-sm-2 col-form-label">Testimonial</label>
                        <div class="col-sm-10">
                            <textarea name="testimonial" id="testimonial" class="form-control"></textarea>
                            <div class="text-danger error-message" id="testimonial-error"></div>
                        </div>
                    </div>
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-dark">Add </button>
                    </div>
                    </div>
            </form>
            
        </div>
    </div>
</main>

{% endblock %}

templates/kaps_admin/add_products.html
{% extends 'kaps_admin/admin_base.html' %}
{% block content %}
{% load static %}

<main id="main" class="main">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Add a new Car</h5>
            <form method="post" enctype="multipart/form-data" id="add-product-form">
                {% csrf_token %}
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Brand name</label>
                    <select id="brand" name="brand" class="form-control" required>
                        {% for brand in Brand_choices %}
                        <option value="{{ brand }}">{{ brand }}</option>
                        {% endfor %}
                      </select>
                </div>
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Colour</label>
                    <div class="col-sm-10">
                        <input type="text" name="colour" id="id_name" class="form-control">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Variant</label>
                    <div class="col-sm-10">
                        <input type="text" name="variant" id="id_name" class="form-control">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Model name</label>
                    <div class="col-sm-10">
                        <input type="text" name="model_name" id="id_name" class="form-control">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_description" class="col-sm-2 col-form-label">Description</label>
                    <div class="col-sm-10">
                        <textarea name="description" id="id_description" class="form-control"></textarea>
                        <div class="text-danger error-message" id="description-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Selling Price</label>
                    <div class="col-sm-10">
                        <input type="text" name="price" id="id_price" class="form-control">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Milage</label>
                    <div class="col-sm-10">
                        <input type="text" name="milage" id="id_name" class="form-control">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Transmission type</label>
                    <select id="transmission" name="transmission" class="form-control" required>
                        {% for trans_type in transmission_choices %}
                        <option value="{{ trans_type }}">{{ trans_type }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Inspect rating</label>
                    <div class="col-sm-10">
                        <input type="text" name="inspection" id="id_name" class="form-control" placeholder="Rate out of 10">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Reg. Year</label>
                    <div class="col-sm-10">
                        <input type="text" name="reg_year" id="id_name" class="form-control">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Reg. Month</label>
                    <div class="col-sm-10">
                        <input type="text" name="reg_month" id="id_name" class="form-control">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">KM Driven</label>
                    <div class="col-sm-10">
                        <input type="text" name="km" id="id_name" class="form-control">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">RTO</label>
                    <div class="col-sm-10">
                        <input type="text" name="rto" id="id_name" class="form-control">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_insure_validity" class="col-sm-2 col-form-label">Insurance validity</label>
                    <div class="col-sm-10">
                      <input type="date" name="insure_validity" id="id_insure_validity" class="form-control" placeholder="YYYY-MM-DD">
                      <div class="text-danger error-message" id="name-error"></div>
                    </div>
                  </div>
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Insurance Type</label>
                    <div class="col-sm-10">
                        <input type="text" name="insure_type" id="id_name" class="form-control">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Number of owners</label>
                    <div class="col-sm-10">
                        <input type="text" name="owner" id="id_name" class="form-control">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Fuel type</label>
                    <select id="fuel" name="fuel" class="form-control" required>
                        {% for fuel_type in fuel_choices %}
                        <option value="{{ fuel_type }}">{{ fuel_type }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="row mb-3">
                    <label for="id_emi" class="col-sm-2 col-form-label">Emi</label>
                    <div class="col-sm-10">
                      <select name="emi" id="id_emi" class="form-control">
                        <option value="">Select</option>
                        <option value="yes">Yes</option>
                        <option value="no">No</option>
                      </select>
                      <div class="text-danger error-message" id="emi-error"></div>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Engine rating</label>
                    <div class="col-sm-10">
                        <input type="text" name="engine" id="id_name" class="form-control" placeholder="Rate out of 10">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Suspension rating</label>
                    <div class="col-sm-10">
                        <input type="text" name="suspension" id="id_name" class="form-control" placeholder="Rate out of 10">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Brakes rating</label>
                    <div class="col-sm-10">
                        <input type="text" name="barke" id="id_name" class="form-control" placeholder="Rate out of 10">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Transmission rating</label>
                    <div class="col-sm-10">
                        <input type="text" name="transmission_rate" id="id_name" class="form-control" placeholder="Rate out of 10">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Interior rating</label>
                    <div class="col-sm-10">
                        <input type="text" name="interior" id="id_name" class="form-control" placeholder="Rate out of 10">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>

                <div class="row mb-3">
                    <label for="id_name" class="col-sm-2 col-form-label">Wheel tyre rating</label>
                    <div class="col-sm-10">
                        <input type="text" name="wheels" id="id_name" class="form-control" placeholder="Rate out of 10">
                        <div class="text-danger error-message" id="name-error"></div>
                    </div>
                </div>
    
                <div class="row mb-3">
                    <label for="id_images" class="col-sm-2 col-form-label">Images</label>
                    <div class="col-sm-10">
                        <input type="file" name="images" id="id_images" class="form-control" multiple required onchange="handleImageUpload(this.files)">
                        <div class="error-message" id="images-error"></div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-sm-2"></div>
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-dark">Add Product</button>
                    </div>
                </div>
            </form>
            
        </div>
    </div>
</main>

{% endblock %}

templates/kaps_admin/admin_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Login</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            margin: 0;
            padding: 0;
            height: 100vh;
            background: linear-gradient(180deg, #464646 0%, #000000 100%);
            display: flex;
            justify-content: center;
            align-items: center;
            font-family: Arial, sans-serif;
        }
        .admin-login-container {
            width: 90%;
            max-width: 719px;
            height: 513px;
            max-height: 513px;
            background-color: rgba(0, 0, 0, 0.65);
            padding: 20px;
            border-radius: 21px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        .admin-login-form {
            width: 100%;
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
        }
        .admin-login-form img {
            width: 150px;
            margin-bottom: 30px;
        }
        .admin-login-form input {
            width: 100%;
            max-width: 489px;
            height: 70px;
            margin-bottom: 30px;
            padding: 10px;
            border: 0.5px solid #787878;
            border-radius: 10px;
            box-shadow: 0 4px 20px 0 rgba(94, 94, 94, 0.25);
            background-color: #161616;
            color: white;
            font-size: 16px;
            box-sizing: border-box;
        }
        .admin-login-form input::placeholder {
            color: #787878;
        }
        .admin-login-form button {
            width: 100%;
            max-width: 117px;
            height: 39px;
            background-color: #7FBDB9;
            border: none;
            border-radius: 10px;
            color: white;
            font-size: 16px;
            cursor: pointer;
            margin-top: 20px;
        }
        .admin-login-form button:hover {
            background-color: #6fa9a6;
        }
        @media (max-width: 768px) {
            .admin-login-container {
                width: 100%;
                width: 260px;
                height: 330px;
            }
            .admin-login-form input {
                max-width: 80%;
                height: 45px;
                margin-bottom: 20px;
            }
            .admin-login-form button {
                max-width: 30%;
                height: 35px;
            }
            .admin-login-container {
                width: 95%;
                padding: 10px;
            }
            .admin-login-form img {
                width: 90px;
            }
        }
    </style>
</head>
<body>
    <div class="admin-login-container">
        <form class="admin-login-form" method="post" action="">
            {% csrf_token %}
            <img src="{% static 'admin/images/kaps.svg' %}" alt="Logo">
            <input type="text" name="username" placeholder="Username" required>
            <input type="password" name="password" placeholder="Password" required>
            <button type="submit">Login</button>
        </form>
    </div>
</body>
</html>